config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #  get 'pages/home', to: 'pages#home'
    #get 'pages/about', to: 'pages#about'
    get 'about', to: 'pages#about'
    root :to => 'pages#home'
    #resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy] ##This will give all the articles routes that we need for articles or
    resources :articles ##provide all the rest-ful resources for articles(routes rails resources)
  #  get 'articles/:id/edit', to: 'articles#edit'
#    patch 'articles/:id', to: 'articles#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true , length: { minimum: 10, maximum: 300}
end

app/controllers/PagesController.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
    #byebug
    #@article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    #byebug
    #@article = Article.find(params[:id])
  end


  def create
    #render plain: params[:article]
    # @article = Article.new(params[:article])
    @article = Article.new(article_params)
    #render plain: @article.inspect  #show article objects
    if @article.save
        flash[:notice] = "Article was created successfully."
        redirect_to  @article
    else
        render 'new'
    end
  end

  def update
    #@article = Article.find(params[:id])
    if @article.update(article_params)
        flash[:notice] = "Article updated successfully!"
        redirect_to @article
    else
        render 'edit'
    end
  end

  def destroy
    #byebug
    #@article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being edited</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

<p>
  <%= f.label :title %></br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %></br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and Return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Article listing page</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan=3>Actios</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article), method: :get %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>

    <% end %>
  </tbody>

</table>

<p>
  <%= link_to 'Create New Article', new_article_path %> |
  <%= link_to 'About page', about_path %>
</p>

app/views/articles/new.html.erb
<h1>Create new article</h1>
<%= render 'form' %>
<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing articles details</h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<p>
  <%= link_to 'Edit |', edit_article_path(@article), method: :get %>
  <%= link_to 'Delete |', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>
  <%= link_to 'Return to articles listing', articles_path %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h5>This is my about page</h5>
    <%= link_to 'Home page', root_path %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> This is my home page </h1>
    <%= link_to 'About page', about_path %> |
    <%= link_to 'Return to articles listing', articles_path %>
  </body>
</html>